title: Lyubov Parfilova
author: Lyubov Parfilova
email: cnlmode@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Привет!
  ___
  [!Профиль на HackerRank](https://www.hackerrank.com/lubaro)

# social links
# twitter_username: your-twitter-handle
github_username:  lubaro

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
logo: https://avatars.githubusercontent.com/u/29543596?v=4
